Больше деталей
htmlacademy-javascript/315531-keksobooking-22 pull request #3
Opened 2021-02-04 06:35 UTC by gsem73

2021-02-04 09:12 UTC, MrMeison requested changes

2021-02-04 09:12 UTC, MrMeison commented on js/main.js
> +  let RandomIndex = getRandomInteger(0,elements.length-1)
по неймингу: 
- с большой буквы пишутся только классы, тут стоит использовать camelCase
- между параметрами стоит ставить пробел, иначе оно "слипается"

2021-02-04 09:12 UTC, MrMeison commented on js/main.js
> +let getRandomArray = function(array) {
Для этой штуки лучше использовать вот этот алгоритм - https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle

2021-02-04 09:12 UTC, MrMeison commented on js/main.js
> +  return arrayDuplicate.slice(0, randomLength-1);
Не очень понятно зачем еще один слайс?

2021-02-04 09:12 UTC, MrMeison commented on js/main.js
> +      avatar: 'img/avatars/user' + String(getRandomInteger(1, AVATAR_COUNT)).padStart(2,'0') + '.png',
тут можно просто index  использовать, чтобы аватарки не повторялись

2021-02-05 14:19 UTC, gsem73 commented on js/main.js
> +let getRandomArray = function(array) {
Немного оптимизировал эту функцию: сейчас завершаю "перемешивание" элементов массива, когда подобрано нужное количество элементов в результирующем массиве

2021-02-05 14:19 UTC, gsem73 commented on js/main.js
> +  return arrayDuplicate.slice(0, randomLength-1);
Чтобы избежать изменений во входном массиве, передаваемом в качестве параметра, делалась его копия. Функцию переписал, сейчас остался только один slice

2021-02-05 14:21 UTC, gsem73 commented on js/main.js
> +      avatar: 'img/avatars/user' + String(getRandomInteger(1, AVATAR_COUNT)).padStart(2,'0') + '.png',
Вынес имена файлов в массив, так действительно лучше. По уникальности требования в ТЗ вроде нет, файлов всего восемь, на все объекты уникальных не хватит

2021-02-05 14:22 UTC, gsem73 commented
Спасибо за замечания!

2021-02-07 13:32 UTC, merged